credentials:
  usernames:
    A1:
      email: jsmith@example.com
      name: Anv채ndare A1
      password: '$2b$12$mnJL0fxDbAZjScwaD1N7gONa6AEvE3mONb9sXtz2pE.AEfEAVPRju'
    A2:
      email: rwallace@example.com
      name: Rebecca Wallace
      password: '$2b$12$mnJL0fxDbAZjScwaD1N7gONa6AEvE3mONb9sXtz2pE.AEfEAVPRju'
  cookie:
    expiry_days: 30
    key: 'some_signature_key' # Byt g채rna ut denna mot en slumpm채ssig str채ng
    name: 'some_cookie_name'
  preauthorized:
    emails:
    - m.danneman@gmail.com
