credentials:
  usernames:
    A1:
      email: a1@example.com
      name: Användare A1
      password: '$2b$12$TdJODg2sMm6gBkQNuOQY9etncXNjvHAWbBcC9VPoZWXHyOuavYJXe'
    A2:
      email: a2@example.com
      name: Användare A2
      password: '$2b$12$TdJODg2sMm6gBkQNuOQY9etncXNjvHAWbBcC9VPoZWXHyOuavYJXe'
  cookie:
    expiry_days: 30
    key: 'banankalas' # Kan vara vilken textsträng som helst
    name: 'chattbot_cookie'
  preauthorized:
    emails: [] # Kan vara tom
